name: Tests

on: [pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install Node dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
